### ISSUE TITLE
Font Awesome not working in remodal windows

### ISSUE THREAD

**Issue by meivin123** [VodkaBears/Remodal#102]
Hi,
when I first tried to use Font Awesome icons in remodal windows it didnt work.
Now I fixed the bug and I want to share the solution:
You have to comment out the 
```css
.remodal,
.remodal * {
    font-family: "Exo 2", sans-serif;
}
```
rule.

Maybe in future releases theres no standard font anymore.
That would be great cause the most people are using their own fonts.
