### ISSUE TITLE
Make overflow:hidden on body optional

### ISSUE THREAD

**Issue by TiGR** [VodkaBears/Remodal#155]
It would be nice if locking scrolling was optional. The problem is, though I can override it with CSS, I can't prevent remodal from adding padding to content element. Or is there a way?

Remodal works well this way, and I am pretty fine with background scrollable.

**Comment by VodkaBears** [comment]
```
body {
  padding-right: 0 !important;
}
```

**Comment by TiGR** [comment]
So, it takes this to change the behavior:

```css
body {
    padding-right: 0 !important;
|
.html.remodal-is-locked, body.remodal-is-locked {
    overflow: auto;
}
```
