### ISSUE TITLE
Horizontal jump when vertical scrollbar is hidden

### ISSUE THREAD

**Issue by shkolnik** [VodkaBears/Remodal#50]
Thank you for this great library. I just need help with one issue...

I'm using Remodal on a page that is long enough to require vertical scrolling (at least on smaller monitors). I'm using the default styles, including:

``` css
html.remodal_lock,
body.remodal_lock {
    overflow: hidden;
}
```

As expected this causes the browser to remove the scrollbar. The problem I'm having is that my page responds to the new viewport size and jumps about 20-30px to the right when the modal is displayed.

Is there an easy/known way to mitigate this effect?

**Comment by Garrett-R** [comment]
I think this issue should be reopened.  Adding:
```css
html, body {
    overflow: auto !important;
}
```
is not a good solution since other elements may also be relying on `overflow`.
